/*  Measure generated by a storage node which detects one or more expired sensor
*/
#ifndef __BLACKLIST_MESSAGE_H__  
#define __BLACKLIST_MESSAGE_H__  

#include <vector>
#include <iostream>

#include "message.h"

class BlacklistMessage : public Message {
 private:
  int hop_counter_;
  
 public: 
  BlacklistMessage();
  BlacklistMessage(std::vector<unsigned int>);
  
  std::vector<unsigned int> sensor_ids_;	// contains the ids of the expired sensors

  int get_hop_counter() {return hop_counter_;}
  int increase_hop_counter();
  unsigned int get_message_size();
};

#endif

