#ifndef __SENSOR_NODE_H__   
#define __SENSOR_NODE_H__  

#include "node.h"
#include "storage_node.h"
#include "measure.h"

using namespace std;

class SensorNode: public Node {

  Measure measure_;   // measure generated by the sensor
  StorageNode my_supervisor_;
  int measure_id_;

 public:
  SensorNode (int node_id) : Node (node_id) {measure_id_ = 0;}
  SensorNode (int node_id, double y_coord, double x_coord) : Node (node_id, y_coord, x_coord) {measure_id_ = 0;}

  void set_measure(Measure);
  Measure get_measure() {return measure_;}
  void generate_data();
};

#endif
